### ISSUE TITLE
Failing to receive the Red channel using an RTL-SDR V.3

### ISSUE THREAD

**Issue by JoshuaKimsey** [dvdesolve/glrpt#10]
So I have been able to receive QPKS signals from the Meteor M2 satellite over the past couple days, with the pass tonight being the best I've gotten so far despite me discovering the Meteor M2 is visible only. But hey, the dark side of the Earth is cool! xD

One issue though, each time I've tried, I don't receive the Red channel, Channel 0, of the three I know are supposed to be received. I get the Green and Blue channels, Channel 1 & Channel 2, and those combine to make a sorta trippy blue-green composite image. Do you know why I'm not receiving the Red channel from Meteor M2? Is it something settings wise with my RTL-SDR I need to work with in the configs? I followed the German tutorial and set my bandwidth to 130 as he suggested, though I have no clue if that affects the different channels.

Let me know if you need any other info or log files. I also have some images I received I can share too if that would help you diagnose the problem.

**Comment by dvdesolve** [comment]
Currently Meteor-M2 uses 125 mode (you can check it with link in readme.md)
so you should specify correct image APIDs in config file

73, Viktor

чт, 29 окт. 2020 г., 7:25 Joshua Kimsey <notifications@github.com>:

**Comment by JoshuaKimsey** [comment]
Ok, now I think I understand how this works. Just help me figure this out real quick. Here are the current APID modes active:
![Screenshot-20201029004744-409x679](https://user-images.githubusercontent.com/22421310/97526848-6838e700-1980-11eb-9a75-efdb6fe89dff.png)

With this in formation how do I set the APID numbers correctly in the config file? I don't totally understand how to set the channels right for each one. Here is what the default settings were for M2:
![Screenshot-20201029004937-729x400](https://user-images.githubusercontent.com/22421310/97526978-a209ed80-1980-11eb-9a97-0617bb0deba0.png)

After this, I should be able to set the APID's on my own whenever they change. :)

**Comment by dvdesolve** [comment]
you should specify apid numbers from longest wavelengths to the shortest.
they will correspond to the Internal Channels 0, 1 and 2 of glrpt. usually
apid 66 is the longest wavelength so it will be placed first followed by 65
and 64. now apid 68 (infrared channel) is doing it's business so it will be
for Channel 0. your final parameter should be [68, 65, 64]

73, Viktor

чт, 29 окт. 2020 г., 7:50 Joshua Kimsey <notifications@github.com>:

**Comment by JoshuaKimsey** [comment]
Awesome! Thank you so much! Should I mess with the inverted channels at all? Or leave those alone for now?

**Comment by dvdesolve** [comment]
you can leave them as they are. it's only needed for extra image
refinement. for example, with your settings channel 0 will be inverted
before merging.
IMHO it's better to use grayscale images while in 125 mode because
colorization of IR channel will give somewhat unusual pictures. in any case
you should provide correct APIDs to get properly decided channels

73, Viktor

чт, 29 окт. 2020 г., 7:56 Joshua Kimsey <notifications@github.com>:

**Comment by JoshuaKimsey** [comment]
Awesome! Thanks for your help! :)
