### ISSUE TITLE
SoapySDR.c:596:9: error: too many arguments to function ‘SoapySDRDevice_setupStream’

### ISSUE THREAD

**Issue by Kannagimoe** [dvdesolve/glrpt#12]
![Screenshot from 2020-12-29 23-40-18](https://user-images.githubusercontent.com/5789081/103320936-42d36280-4a2f-11eb-9340-3caa04f0db30.png)

I can't seem to get passed this, which is a shame since I would love to be able to use this application.

**Comment by dvdesolve** [comment]
please see #7 - it's related to the unstable soapy version in your distro
