### ISSUE TITLE
No package 'gtk+-3.0' found

### ISSUE THREAD

**Issue by benb0jangles** [dvdesolve/glrpt#14]
Im getting:

configure: error: Package requirements (gtk+-3.0 >= 3.22.0) were not met:

No package 'gtk+-3.0' found

How to solve please?
dpkg -l libgtk2.0-0 libgtk-3-0

Shows 3.22.30:

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libgtk-3-0:arm 3.22.30-1ubu arm64        GTK+ graphical user interface lib
ii  libgtk2.0-0:ar 2.24.32-1ubu arm64        GTK+ graphical user interface lib

Is it possible to install glrpt using 3.22.30 somehow?

**Comment by dvdesolve** [comment]
Please provide file list of libgtk-3-0 package

**Comment by benb0jangles** [comment]
solved:
sudo apt install libgtk-3-dev
