### ISSUE TITLE
glrpt: Failed to add objects to builder

### ISSUE THREAD

**Issue by benb0jangles** [dvdesolve/glrpt#15]
In terminal: glrpt

glrpt: Failed to add objects to builder:
Failed to open file "/home/benji/glrpt/glrpt.glade": No such file or directory

It seems that glrpt installed glrpt.glade as:
/home/benji/glrpt/glrpt/glrpt.glade

How to correct this please?

**Comment by dvdesolve** [comment]
seems like `CMAKE_INSTALL_DATAROOTDIR` is messed up. By default it should install in `/usr/share` and in your case we have your home directory + glrpt instead

**Comment by benb0jangles** [comment]
simply move the files from:
/home/benji/glrpt/glrpt/
to
/home/benji/glrpt/

Working glrpt-2.5.2 thanks
