### ISSUE TITLE
XWXAPT > GLRPT > HRPT

### ISSUE THREAD

**Issue by benb0jangles** [dvdesolve/glrpt#17]
So my natural question is, is there any interest in HRPT Decoder/Demodulator? 
I see there is big demodulator choice for L-Band on github:
https://github.com/altillimity/L-Band-Decoders
and Image decoder:
https://satsignal.eu/software/hrpt.htm

**Comment by dvdesolve** [comment]
Thank you for pointing that out. I think this may be the aim for separate project. Currently in mlrpt/glrpt we're focusing on LRPT signals only. In the near future there is a plan to release separate `liblrpt` library for crossplatform usage and mlrpt/glrpt will be based on it.
Personally I have no hardware setup for HRPT for now so I can't do any real testing. May be in near future...

**Comment by benb0jangles** [comment]
Same, my HRPT experiments have old aluminium pot, and copper wire - it did not produce a result in SDR. I have thought a little about checking scrap yards for old satellite dish - once a signal can be received, it is ok to think more.
