### ISSUE TITLE
MacOs: No package 'gtk+-3.0' found

### ISSUE THREAD

**Issue by benb0jangles** [dvdesolve/glrpt#18]
I'm getting this error compiling on MacOs:

Command:
cmake -DCMAKE_INSTALL_PREFIX=/usr ..

error:
...
-- Checking for module 'gtk+-3.0>=3.22.0'
--   No package 'gtk+-3.0' found
CMake Error at /opt/local/share/cmake-3.19/Modules/FindPkgConfig.cmake:553 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/local/share/cmake-3.19/Modules/FindPkgConfig.cmake:741 (_pkg_check_modules_internal)
  src/CMakeLists.txt:6 (pkg_check_modules)

-- Configuring incomplete, errors occurred!

However, when I run:
brew install gtk+3

I get:
Warning: gtk+3 3.24.29 is already installed and up-to-date.
To reinstall 3.24.29, run:
  brew reinstall gtk+3

Please, what think happening?

**Comment by dvdesolve** [comment]
I'm not familiar with Apple ecosystem but it seems like your GTK package doesn't provide required pkgconfig files or install them in another place. May be you should install some kind of development package which will provide necessary files?

**Comment by benb0jangles** [comment]
I could only find:
brew install gtk+3

But I could not find:
libgtk-3-dev package for mac :(

Thanks for replying

**Comment by dvdesolve** [comment]
[There is](https://www.programmersought.com/article/38922134574/) an example of using CMake and GTK3 on MacOS. Seems like package name is right. But may be `PKG_CONFIG_PATH` is incorrect, you should check it by yourself. More info [here](https://stackoverflow.com/questions/20098862/how-to-install-gtk-on-osx-for-use-with-g-gcc-compiler)

**Comment by benb0jangles** [comment]
Solved working on MacOS Sierra 10.12.6:
Had to set the PKG_CONFIG_PATH.

install gtk3:
`brew install gtk+3`
`export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig`

Check with:
```
pkg-config gtk+-3.0 --exists && echo Found the library
(no output means the .pc file not found)
```

`pkg-config gtk+-3.0 --libs --print-errors`
(error message, or long list of flags =success)

Install these dependencies:
    gtk+ (3.22.0 or higher)
    glibc
    glib2
    SoapySDR (install proper modules to get support for your hardware)
    libjpeg-turbo
    libconfig
    gcc (4.8 or higher) / clang (3.1 or higher)
    make
    cmake (3.12 or higher)

GLRPT 2.6.0 MacOs:
```
git clone https://github.com/dvdesolve/glrpt.git
cd glrpt
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
sudo make install
```

Run in terminal using: 
`glrpt`

**Comment by benb0jangles** [comment]
![Screen Shot 2021-04-27 at 17 48 19](https://user-images.githubusercontent.com/15876842/116280672-d79d6100-a780-11eb-8cf1-8495c05fb4fd.png)

**Comment by benb0jangles** [comment]
![Screen Shot 2021-04-27 at 17 50 07](https://user-images.githubusercontent.com/15876842/116280900-103d3a80-a781-11eb-95f2-e3322f4027fd.png)

**Comment by benb0jangles** [comment]
```
-DCMAKE_INSTALL_PREFIX=/usr ..
gmodule
-- Checking for module 'gtk+-3.0>=3.22.0'
--   Found gtk+-3.0, version 3.24.29
-- Checking for module 'SoapySDR'
--   Found SoapySDR, version 0.8.0
-- Checking for module 'libturbojpeg'
--   Found libturbojpeg, version 2.0.6
-- Checking for module 'libconfig'
--   Found libconfig, version 1.7.2
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/username/glrpt/build
```

**Comment by benb0jangles** [comment]
Install SoapySDR + Devices:
`sudo port install SoapySDR SoapyAirspy SoapyAudio SoapyHackRF SoapyRemote SoapyRTLSDR SoapySDRPlay SoapyUHD`
