### ISSUE TITLE
Not finding libturbojpeg but it is installed

### ISSUE THREAD

**Issue by HemiBob** [dvdesolve/glrpt#22]
I'm following the instructions and my system is showing as not found.

bob@3040-i5:~/Downloads/glrpt-2.6.1/build$ sudo cmake -DCMAKE_INSTALL_PREFIX=/usr ..
gmodule
-- Checking for module 'libturbojpeg'
--   No package 'libturbojpeg' found
CMake Error at /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:603 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPkgConfig.cmake:825 (_pkg_check_modules_internal)
  src/CMakeLists.txt:8 (pkg_check_modules)
###########################
But when I try to install it I get:
bob@3040-i5:~/Downloads/glrpt-2.6.1/build$ sudo apt install libturbojpeg
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libturbojpeg is already the newest version (2.1.2-0ubuntu1).

What can I do to solve this please?
Operating system: Linux Ubuntu 22.04

**Comment by dvdesolve** [comment]
can you please provide full info about your `libturbojpeg` version and full lists of files installed by this package?
