### ISSUE TITLE
Decoding doesn't seem to combine the images correctly

### ISSUE THREAD

**Issue by JohnCC330** [dvdesolve/glrpt#25]
When I finally got `lrpt` running more smoothly, I see that the images are ordered in a strange - cyclic - way:

![Screenshot_2023-11-28_14-18-11](https://github.com/dvdesolve/glrpt/assets/3728987/8e77213f-00c7-46f5-ac6f-a90e4e0076fe)

Is this Meteor's, lrpt's or - most probably - my fault?

**Comment by dvdesolve** [comment]
there were some problems recently with the satellite. however you can recheck yourself to be on safe side - just consult US radioguy page to get current working apids and set them properly in config file
