### ISSUE TITLE
Signal quality bar is shown even when no image is being received

### ISSUE THREAD

**Issue by BaumGuard** [dvdesolve/glrpt#6]
In the recent version 2.6.0, a green bar for the signal quality is shown, although no image is being received. I've already asked Neoklis and he said that the noise level is too low if no antenna is connected causing the pll to be locked wrongly. But it doesn't change even if an antenna is connected. I haven't had that problem in the version 2.4.5.

**Comment by dvdesolve** [comment]
thank you for pointing that out. signal quality bar activates when pll locks. previous equation used to calculate signal level was wrong and gave negative values which were transformed to 0 value of signal level indicator. as a result there was impression that signal bar "disappears". now I've fixed the formula but it seems like we should manually set signal quality to 0 when pll unlocks. I'll take a look soon
