### ISSUE TITLE
trouble during make

### ISSUE THREAD

**Issue by AlexShuvalov** [dvdesolve/glrpt#7]
I am trying to install glrpt. During make i've got following error:

`SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,`
                               `^~~~~~~~~~~~~~~~~~~~~~~~~~`
`/home/alexandr/Dev/glrpt-2.6.0/src/sdr/SoapySDR.c:594:9: error: too many arguments to function ‘SoapySDRDevice_setupStream’`
`   ret = SoapySDRDevice_setupStream(`
`         ^~~~~~~~~~~~~~~~~~~~~~~~~~`
`In file included from /home/alexandr/Dev/glrpt-2.6.0/src/sdr/SoapySDR.c:29:`
`/usr/local/include/SoapySDR/Device.h:295:31: note: declared here`

I compare /home/alexandr/Dev/glrpt-2.6.0/src/sdr/SoapySDR.c:594:

` ret = SoapySDRDevice_setupStream(`
`      sdr, &rxStream, SOAPY_SDR_RX, SOAPY_SDR_CS16, NULL, 0, NULL );`

and /usr/local/include/SoapySDR/Device.h:295:

`SOAPY_SDR_API SoapySDRStream *SoapySDRDevice_setupStream(SoapySDRDevice *device,`
`    const int direction,`
`    const char *format,`
`    const size_t *channels,`
`    const size_t numChans,`
`    const SoapySDRKwargs *args);`

Argument list seems to be really different. Am I doing something wrong? Please help.

All previous steps end normally

OS: debian 10.

**Comment by dvdesolve** [comment]
seems like you have staging/beta version of SoapySDR installed. Could you please tell me which version are you using? latest stable version is 0.7.2 and it's working just fine. newer versions have broken API compatibility. We'll fix it soon

**Comment by AlexShuvalov** [comment]
Yes, you are right. SoapySDR was 0.8. I change SoapySDR to 0.7.2, then glrpt begin to work. The problem solved.
Thank You very much!

**Comment by dvdesolve** [comment]
I think as soon as Soapy will stabilize then we implement necessary changes. Thank you for raising this up!

**Comment by dvdesolve** [comment]
Fixed in fff40fe
